### ISSUE TITLE
amdgpu DRM support ?

### ISSUE THREAD

**Issue by aaaldo** [D0023R/linux_kernel_15khz#1]
Hello @D0023R thanks for the great job made on porting this fix over the newer kernels. As you seems to understand more than I do this topic, do you think it's possible to port this patch over the amdgpu driver as well ? This could be an interesting option for newer AMD GPU or APU.

**Comment by D0023R** [comment]
Hi,
I do not own an amdgpu to confirm the following is working, but I do not see any reason why it would not work for you.
The Linux kernel has a dkms helper to override the EDID information normally provided by the screen/monitor to the video card. It is possible to feed a pre-made EDID (15KHz with custom resolution) to the card when booting Linux without patching the kernel. (add the edid binary under /lib/firmware/edid/ and append the following to your kernel "video=VGA-1:e drm_kms_helper.edid_firmware=VGA-1:edid/edid.bin")
Ansa89 has made some 15KHz EDID you can find on his repository. EDID editor tools exist to create or set you own modelines. 
Xorg will use the EDID configured resolution as baseline and DRM can be used via Xrandr to set different custom modes at runtime.

**Comment by aaaldo** [comment]
Hi @D0023R thanks for the answer è I'll try your patch on the 5.0.6 kernel and test it so.

**Comment by aaaldo** [comment]
Hi @D0023R ! FYI, i managed to successfully patch the 4.18.20 kernel (default kernel for the lastest Ubuntu - version 18.10) and i confirm that the fix is also working on the AMD Athlon 200GE !
Thanks again for the tip and the work on this repo. Cheers !
