### ISSUE TITLE
Rename patch file extensions to .patch?

### ISSUE THREAD

**Issue by shawly** [D0023R/linux_kernel_15khz#6]
Hey!

I'm currently trying to assemble a custom build of Recalbox with your 15KHz patches to make the OS fully 15KHz compatible.
Recalbox uses buildroot to build the OS, where one can set paths to patch folders with the BR2_LINUX_KERNEL_PATCH variable.

The thing is the [linux.mk](https://git.busybox.net/buildroot/tree/linux/linux.mk#n251) file only applies files that are have the .patch file extension. The ones here use .diff.

I'd have to write a script that renames the file endings from .diff to .patch which is not a problem in it self. But I wondered if you'd be willing to rename the file extensions to .patch so people can use your repo via git submodules and just apply the patches automatically without modifying anything.

Thanks!

**Comment by D0023R** [comment]
Hi Shawly,

I agree with the fact that the suffix diff is not well aligned with the commonly used kernel modifications. Knowing that the file extension to be used is indeed dot patch, the repository has been updated to follow this common rule. 
You can now use the linux.mk tool with the files to include the 15kHz patches. 

Thanks for having reported this. Cheers!
