### ISSUE TITLE
Contact Request

### ISSUE THREAD

**Issue by bobbymerde** [D0023R/linux_kernel_15khz#8]
Hi Doozer,

sorry for misusing this feature, but I had no idea how else I could get in contact with you.

I stumbled upon you on the arcadecontrols forum while I was searching for a way to get the scanout position. For my Bachelors Thesis, knowing the position of the scanout would be very helpful. If you could answer some questions for me, I would be very thankful.

Since I don't want to continue misusing the issues page, please respond to my university email address: Jonas.Mertenbaur@stud.hs-coburg.de.

Thank you in advance for your consideration

**Comment by D0023R** [comment]
Closed as per request.

**Comment by D0023R** [comment]
Closed as per request.

**Comment by D0023R** [comment]
Closed as per request
