### ISSUE TITLE
Scanout position

### ISSUE THREAD

**Issue by Grieverheart** [D0023R/linux_kernel_15khz#9]
I'm trying to get the scanout position in Linux for a personal project. Is the code in `linux_15khz_scanoutpos.patch` the easiest way to get that, or do you know if there are other userspace methods for acquiring this information?

**Comment by D0023R** [comment]
Hi,
To my knowledge there is no userspace method that could provide the scanout position. 
An alternative method would be to use vblank to start a timer and calculate the delay a beam would have reach a certain position (based on the porch and refresh values). This would also relax the pressure from polling the kernel for the position.
Hope it helps.

**Comment by Grieverheart** [comment]
> An alternative method would be to use vblank to start a timer and calculate the delay a beam would have reach a certain position (based on the porch and refresh values). 

Would you first set vsync to on to start the timer and then turn it off? Also, from my understanding there is some jitter between when the driver does the presentation and when the pixels are shown on screen. I guess you could sample a few vblanks to try to infer the timing more accurately.

I also did some research about the different possibilities, and found out that one could use the OpenGL extensions GLX_SGI_video_sync or GLX_OML_sync_control, or use the Vulkan extension VK_GOOGLE_display_timing, but support is still bad on the last one, and the first two require OpenGL and I'd like to use Vulkan. Then, you also have VK_EXT_display_control but I keep getting an error when trying to call vkGetSwapchainCounterEXT. Do you have experience with any of this?

In the end, my goal is to find out if I can use an embedded GPU for scaling retro video games with minimal latency, so a custom kernel would definitely be an option.

**Comment by D0023R** [comment]
> > An alternative method would be to use vblank to start a timer and calculate the delay a beam would have reach a certain position (based on the porch and refresh values).
> 
> Would you first set vsync to on to start the timer and then turn it off? Also, from my understanding there is some jitter between when the driver does the presentation and when the pixels are shown on screen. I guess you could sample a few vblanks to try to infer the timing more accurately.
> 

No need to manipulate the vsync, just use the drmWaitVBlank io call to get notified about next vblank. You can check but the timing should be pretty accurate. Reset the timer at each vblank and you should be ready to chase the beam.  

> I also did some research about the different possibilities, and found out that one could use the OpenGL extensions GLX_SGI_video_sync or GLX_OML_sync_control, or use the Vulkan extension VK_GOOGLE_display_timing, but support is still bad on the last one, and the first two require OpenGL and I'd like to use Vulkan. Then, you also have VK_EXT_display_control but I keep getting an error when trying to call vkGetSwapchainCounterEXT. Do you have experience with any of this?
> 
MESA/SDL libraries have some king of blanking exposed functionality. Sometimes with their own caveat about how it is implemented. They rely on the kernel DRM but you will have to work out their limitation (e.g. SDL mode switching not following new CRTC timing).

> In the end, my goal is to find out if I can use an embedded GPU for scaling retro video games with minimal latency, so a custom kernel would definitely be an option.

Talking retro games (assuming 15kHz is the desired target), AMD APU can be used for this. The limitation is more on the hardware side and the minimum dotclock achievable. Have you already looked at Swtichres ? I think it is doing exactly what you are looking for. It enhances mame (GroovyMame) and RetroArch to provide pixel perfect/refresh video output. You can use the library with LCD as well to calculate best refresh for the original resolution.

**Comment by Grieverheart** [comment]
> No need to manipulate the vsync, just use the drmWaitVBlank io call to get notified about next vblank. You can check but the timing should be pretty accurate. Reset the timer at each vblank and you should be ready to chase the beam.

I've been trying to do that after seeing your comment, but I have been unable to properly `drmOpen` the nvidia-drm driver. There are also open source kernel modules, but unfortunately my GPU is not supported. To be honest, I'd like to drop nvidia for an alternative, but to the best of my knowledge, there are not many other embedded GPU offerings that also have video input (e.g. MIPI CSI-2).

> Talking retro games (assuming 15kHz is the desired target), AMD APU can be used for this. The limitation is more on the hardware side and the minimum dotclock achievable.

I had a look at the AMD APU boards, but can't find one with a good video input interface. One of them seems to have such an interface but only sells boards in bulk.

> Have you already looked at Swtichres ? I think it is doing exactly what you are looking for. It enhances mame (GroovyMame) and RetroArch to provide pixel perfect/refresh video output. You can use the library with LCD as well to calculate best refresh for the original resolution.

Hm, not sure how it exactly works, but I think I need something even more flexible. The idea is to receive the input source scanline by scanline and raster the upscaled scanlines as fast as possible so as to have minimal lag (less than 1 frame on average).

**Comment by D0023R** [comment]
This repo only provides 15Khz video output feature for the internal kernel drivers, not for the proprietary blobs. Btw NVIDIA proprietary driver DRM layer is known to be a hit and miss depending on the driver release and kernel revision. 

> find a good video input interface

I am confused by your statement. Your original post is talking about scanout position (raster scan out). I understand now that you are trying to capture the incoming beam position. On modern interfaces, the rendering is based on rolling raster scan which is done per line and not as a beam. A dedicated chip or FPGA implementation seems to be required to achieve your goal.

> Hm, not sure how it exactly works, but I think I need something even more flexible. The idea is to receive the input source scanline by scanline and raster the upscaled scanlines as fast as possible so as to have minimal lag (less than 1 frame on average).

Unfortunately your scope is not related to the kernel but to the HW doing the capture. You should have a look at the Open Source Scan Converter (OSSC) project (https://videogameperfection.com/products/open-source-scan-converter or the pro version https://videogameperfection.com/products/ossc-pro/).

**Comment by D0023R** [comment]
Closed as not being related to a code issue.
